# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec6c830d14f9c23b2f89f8fa2c19bf11ddf1c90430eab4e0aebad38324953d97f3053f957d87e5f37c8a0032b42c844a5422404df3620e5cd3d4659cebe01f6

test:
  secret_key_base: 47a324a45c6d5542cd47bb929e05e3b00832662ab4c26a5f33499db00dfccc1b9cb182fbf2973cfe0a759f854594c55bdb79e7277dc0dde778a527f14f8f1dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
